"""update dm_attributes

Revision ID: 44fd7bbe37d1
Revises: 4524ff81c146
Create Date: 2025-09-02 19:35:27.186963

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "44fd7bbe37d1"
down_revision = "4524ff81c146"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dm_attributes_v2",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("anchor", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("data_example", sa.String(), nullable=True),
        sa.Column("embeddable", sa.Boolean(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("dtype", sa.String(), nullable=True),
        sa.Column("embed_threshold", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", "anchor"),
    )
    op.create_table(
        "dm_attributes_v2_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("anchor", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", "anchor"),
    )
    op.rename_table(
        "ensure_memgraph_indexes_783e90e30d_meta",
        "ensure_memgraph_indexes_2de7695278_meta",
    )
    op.rename_table(
        "filter_grist_nodes_b185c84840_meta",
        "filter_grist_nodes_fa210a37e8_meta",
    )
    op.drop_table("dm_attributes_meta")
    op.drop_table("dm_attributes")
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrade is not supported.")
