"""edit vector configuration

Revision ID: 513bf0d273b0
Revises: 2dfad73e5cce
Create Date: 2025-12-18 14:59:59.633553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "513bf0d273b0"
down_revision: Union[str, None] = "2dfad73e5cce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ensure_memgraph_edge_indexes_4b7fc56c1d_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "ensure_memgraph_node_indexes_0926b0c60b_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "generate_embeddings_38d4236c15_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "generate_embeddings_e51be7175e_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.drop_table("ensure_memgraph_node_indexes_ec2e99917e_meta")
    op.drop_table("ensure_memgraph_edge_indexes_3ad015600c_meta")
    op.drop_table("generate_embeddings_0fb9cb4570_meta")
    op.drop_table("generate_embeddings_76c1b0fdae_meta")
    op.drop_table("memgraph_link_vector_indexes_meta")
    op.drop_table("memgraph_anchor_vector_indexes_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memgraph_anchor_vector_indexes_meta",
        sa.Column("anchor", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("anchor", "attribute_name", name=op.f("memgraph_anchor_vector_indexes_meta_pkey")),
    )
    op.create_table(
        "memgraph_link_vector_indexes_meta",
        sa.Column("link", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("link", "attribute_name", name=op.f("memgraph_link_vector_indexes_meta_pkey")),
    )
    op.create_table(
        "generate_embeddings_76c1b0fdae_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id", "to_node_id", "edge_label", name=op.f("generate_embeddings_76c1b0fdae_meta_pkey")
        ),
    )
    op.create_table(
        "generate_embeddings_0fb9cb4570_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type", name=op.f("generate_embeddings_0fb9cb4570_meta_pkey")),
    )
    op.create_table(
        "ensure_memgraph_edge_indexes_3ad015600c_meta",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", name=op.f("ensure_memgraph_edge_indexes_3ad015600c_meta_pkey")),
    )
    op.create_table(
        "ensure_memgraph_node_indexes_ec2e99917e_meta",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", name=op.f("ensure_memgraph_node_indexes_ec2e99917e_meta_pkey")),
    )
    op.drop_table("generate_embeddings_e51be7175e_meta")
    op.drop_table("generate_embeddings_38d4236c15_meta")
    op.drop_table("ensure_memgraph_node_indexes_0926b0c60b_meta")
    op.drop_table("ensure_memgraph_edge_indexes_4b7fc56c1d_meta")
    # ### end Alembic commands ###
