"""fix-pipeline-definition

Revision ID: 2e0c3de5844f
Revises: f16d7c1b6d8f
Create Date: 2025-08-13 19:17:04.581254

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e0c3de5844f"
down_revision = "f16d7c1b6d8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prepare_edges_d5fc9dd5c0_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.drop_table("prepare_edges_c225902fe6_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prepare_edges_c225902fe6_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id", "to_node_id", "edge_label", name=op.f("prepare_edges_c225902fe6_meta_pkey")
        ),
    )
    op.drop_table("prepare_edges_d5fc9dd5c0_meta")
    # ### end Alembic commands ###
