"""rm_filtering_steps

Revision ID: 2d3a66f5e43a
Revises: 44fd7bbe37d1
Create Date: 2025-09-04 17:42:24.144359

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d3a66f5e43a"
down_revision: Union[str, None] = "44fd7bbe37d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prepare_edges_c225902fe6_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.create_table(
        "prepare_nodes_34bc19d28a_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.drop_table("grist_nodes_filtered")
    op.drop_table("grist_nodes_filtered_meta")
    op.drop_table("grist_edges_filtered")
    op.drop_table("grist_edges_filtered_meta")
    op.drop_table("filter_grist_nodes_fa210a37e8_meta")
    op.drop_table("filter_grist_edges_8e9fdd46a0_meta")
    op.drop_table("prepare_edges_d5fc9dd5c0_meta")
    op.drop_table("prepare_nodes_53d78b4abd_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grist_edges_filtered",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("from_node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id",
            "to_node_id",
            "from_node_type",
            "to_node_type",
            "edge_label",
            name=op.f("grist_edges_filtered_pkey"),
        ),
    )
    op.create_table(
        "prepare_nodes_53d78b4abd_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", name=op.f("prepare_nodes_53d78b4abd_meta_pkey")),
    )
    op.create_table(
        "prepare_edges_d5fc9dd5c0_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id", "to_node_id", "edge_label", name=op.f("prepare_edges_d5fc9dd5c0_meta_pkey")
        ),
    )
    op.create_table(
        "filter_grist_edges_8e9fdd46a0_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id", "to_node_id", "edge_label", name=op.f("filter_grist_edges_8e9fdd46a0_meta_pkey")
        ),
    )
    op.create_table(
        "grist_edges_filtered_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("from_node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id",
            "to_node_id",
            "from_node_type",
            "to_node_type",
            "edge_label",
            name=op.f("grist_edges_filtered_meta_pkey"),
        ),
    )
    op.create_table(
        "grist_nodes_filtered_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type", name=op.f("grist_nodes_filtered_meta_pkey")),
    )
    op.create_table(
        "grist_nodes_filtered",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type", name=op.f("grist_nodes_filtered_pkey")),
    )
    op.create_table(
        "filter_grist_nodes_fa210a37e8_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", name=op.f("filter_grist_nodes_b185c84840_meta_pkey")),
    )
    op.drop_table("prepare_nodes_34bc19d28a_meta")
    op.drop_table("prepare_edges_c225902fe6_meta")
    # ### end Alembic commands ###
