"""rm memgraph vector indices

Revision ID: 3c5cc51455c5
Revises: e70f049dd39f
Create Date: 2026-02-18 11:05:26.740966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c5cc51455c5"
down_revision: Union[str, None] = "e70f049dd39f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memgraph_link_vector_indexes")
    op.drop_table("memgraph_anchor_vector_indexes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memgraph_anchor_vector_indexes",
        sa.Column("anchor", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("anchor", "attribute_name", name=op.f("memgraph_anchor_vector_indexes_pkey")),
    )
    op.create_table(
        "memgraph_link_vector_indexes",
        sa.Column("link", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("link", "attribute_name", name=op.f("memgraph_link_vector_indexes_pkey")),
    )
    # ### end Alembic commands ###
