"""add config plane

Revision ID: 32ae51ea6092
Revises: e70f049dd39f
Create Date: 2026-01-20 20:48:01.590097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32ae51ea6092"
down_revision: Union[str, None] = "e70f049dd39f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("committed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branches",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "snapshot_items",
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("blob_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["blobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snapshot_items")
    op.drop_table("branches")
    op.drop_table("snapshots")
    op.drop_table("blobs")
    # ### end Alembic commands ###
