"""jims add external_id

Revision ID: 17f7b4956ca5
Revises: 3c5cc51455c5
Create Date: 2026-04-10 12:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "17f7b4956ca5"
down_revision = "3c5cc51455c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("external_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_threads_external_id"), "threads", ["external_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_threads_external_id"), table_name="threads")
    op.drop_column("threads", "external_id")
    # ### end Alembic commands ###
