"""init

Revision ID: 70ad5a672fae
Revises: 
Create Date: 2026-03-26 15:39:14.941935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70ad5a672fae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_events',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('event_domain', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'event_id')
    )
    op.create_table('threads',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('thread_config', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_threads_contact_id'), 'threads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_threads_external_id'), 'threads', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_external_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_contact_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_table('thread_events')
    # ### end Alembic commands ###
