apiVersion: v1
kind: Service
metadata:
  name: memgraph
spec:
  type: ExternalName
  externalName: host.docker.internal
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ExternalName
  externalName: host.docker.internal
