"""initial

Revision ID: 0752f3cfee39
Revises:
Create Date: 2025-07-22 22:13:09.839898

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0752f3cfee39"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dm_anchors",
        sa.Column("noun", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id_example", sa.String(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("noun"),
    )
    op.create_table(
        "dm_anchors_meta",
        sa.Column("noun", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("noun"),
    )
    op.create_table(
        "dm_attributes",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("anchor", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("data_example", sa.String(), nullable=True),
        sa.Column("embeddable", sa.Boolean(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("dtype", sa.String(), nullable=True),
        sa.Column("embed_threshold", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "dm_attributes_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "dm_links",
        sa.Column("anchor1", sa.String(), nullable=False),
        sa.Column("anchor2", sa.String(), nullable=False),
        sa.Column("sentence", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("anchor1_link_column_name", sa.String(), nullable=True),
        sa.Column("anchor2_link_column_name", sa.String(), nullable=True),
        sa.Column("has_direction", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("anchor1", "anchor2", "sentence"),
    )
    op.create_table(
        "dm_links_meta",
        sa.Column("anchor1", sa.String(), nullable=False),
        sa.Column("anchor2", sa.String(), nullable=False),
        sa.Column("sentence", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("anchor1", "anchor2", "sentence"),
    )
    op.create_table(
        "edges",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "edges_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "ensure_memgraph_indexes_783e90e30d_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "filter_grist_edges_8e9fdd46a0_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.create_table(
        "filter_grist_nodes_b185c84840_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_table(
        "generate_embeddings_634a8be398_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.create_table(
        "generate_embeddings_e949b6491e_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "grist_edges",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "grist_edges_filtered",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "grist_edges_filtered_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "grist_edges_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "grist_nodes",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "grist_nodes_filtered",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "grist_nodes_filtered_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "grist_nodes_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "memgraph_edges_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "memgraph_indexes",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "memgraph_indexes_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "memgraph_nodes_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "memgraph_vector_indexes",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("anchor", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "memgraph_vector_indexes_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "nodes",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "nodes_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "prepare_edges_c225902fe6_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.create_table(
        "prepare_nodes_53d78b4abd_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prepare_nodes_53d78b4abd_meta")
    op.drop_table("prepare_edges_c225902fe6_meta")
    op.drop_table("nodes_meta")
    op.drop_table("nodes")
    op.drop_table("memgraph_vector_indexes_meta")
    op.drop_table("memgraph_vector_indexes")
    op.drop_table("memgraph_nodes_meta")
    op.drop_table("memgraph_indexes_meta")
    op.drop_table("memgraph_indexes")
    op.drop_table("memgraph_edges_meta")
    op.drop_table("grist_nodes_meta")
    op.drop_table("grist_nodes_filtered_meta")
    op.drop_table("grist_nodes_filtered")
    op.drop_table("grist_nodes")
    op.drop_table("grist_edges_meta")
    op.drop_table("grist_edges_filtered_meta")
    op.drop_table("grist_edges_filtered")
    op.drop_table("grist_edges")
    op.drop_table("generate_embeddings_e949b6491e_meta")
    op.drop_table("generate_embeddings_634a8be398_meta")
    op.drop_table("filter_grist_nodes_b185c84840_meta")
    op.drop_table("filter_grist_edges_8e9fdd46a0_meta")
    op.drop_table("ensure_memgraph_indexes_783e90e30d_meta")
    op.drop_table("edges_meta")
    op.drop_table("edges")
    op.drop_table("dm_links_meta")
    op.drop_table("dm_links")
    op.drop_table("dm_attributes_meta")
    op.drop_table("dm_attributes")
    op.drop_table("dm_anchors_meta")
    op.drop_table("dm_anchors")
    # ### end Alembic commands ###
