"""initial

Revision ID: ddaddd8426c7
Revises:
Create Date: 2025-05-23 12:52:46.165619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddaddd8426c7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_events",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("event_domain", sa.String(length=255), nullable=True),
        sa.Column("event_name", sa.String(length=255), nullable=True),
        sa.Column(
            "event_data", postgresql.JSON(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"), nullable=True
        ),
        sa.PrimaryKeyConstraint("thread_id", "event_id"),
    )
    op.create_table(
        "threads",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "thread_config", postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"), nullable=False
        ),
        sa.PrimaryKeyConstraint("thread_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("threads")
    op.drop_table("thread_events")
    # ### end Alembic commands ###
