"""move emb to pgvector

Revision ID: 2dfad73e5cce
Revises: e25e64e0008a
Create Date: 2025-12-15 19:46:44.395241

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2dfad73e5cce"
down_revision: Union[str, None] = "e25e64e0008a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for pgvector column type
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedded_edges",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "embedded_edges_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("from_node_type", sa.String(), nullable=False),
        sa.Column("to_node_type", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "from_node_type", "to_node_type", "edge_label"),
    )
    op.create_table(
        "embedded_nodes",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "embedded_nodes_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "generate_embeddings_0fb9cb4570_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "generate_embeddings_76c1b0fdae_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.create_table(
        "pass_df_to_memgraph_1d4bbbddd8_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.create_table(
        "pass_df_to_memgraph_37de095f96_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "rag_anchor_embeddings",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.Column("embedding", Vector(dim=1024), nullable=False),
        sa.PrimaryKeyConstraint("node_id", "attribute_name"),
    )
    op.create_table(
        "rag_anchor_embeddings_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "attribute_name"),
    )
    op.create_table(
        "rag_edge_embeddings",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.Column("embedding", Vector(dim=1024), nullable=False),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label", "attribute_name"),
    )
    op.create_table(
        "rag_edge_embeddings_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label", "attribute_name"),
    )
    op.create_table(
        "store_pgvector_edges_899a47ab38_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.create_table(
        "store_pgvector_nodes_572246caf2_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.drop_table("generate_embeddings_804e595250_meta")
    op.drop_table("generate_embeddings_1976c99215_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generate_embeddings_1976c99215_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id", "to_node_id", "edge_label", name=op.f("generate_embeddings_1976c99215_meta_pkey")
        ),
    )
    op.create_table(
        "generate_embeddings_804e595250_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type", name=op.f("generate_embeddings_804e595250_meta_pkey")),
    )
    op.drop_table("store_pgvector_nodes_572246caf2_meta")
    op.drop_table("store_pgvector_edges_899a47ab38_meta")
    op.drop_table("rag_edge_embeddings_meta")
    op.drop_table("rag_edge_embeddings")
    op.drop_table("rag_anchor_embeddings_meta")
    op.drop_table("rag_anchor_embeddings")
    op.drop_table("pass_df_to_memgraph_37de095f96_meta")
    op.drop_table("pass_df_to_memgraph_1d4bbbddd8_meta")
    op.drop_table("generate_embeddings_76c1b0fdae_meta")
    op.drop_table("generate_embeddings_0fb9cb4570_meta")
    op.drop_table("embedded_nodes_meta")
    op.drop_table("embedded_nodes")
    op.drop_table("embedded_edges_meta")
    op.drop_table("embedded_edges")
    # ### end Alembic commands ###
