"""refactor datamodel

Revision ID: e25e64e0008a
Revises: 7e6b7d0b54d1
Create Date: 2025-11-05 10:38:42.924255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e25e64e0008a"
down_revision: Union[str, None] = "7e6b7d0b54d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dm_anchor_attributes",
        sa.Column("anchor", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("data_example", sa.String(), nullable=True),
        sa.Column("embeddable", sa.Boolean(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("dtype", sa.String(), nullable=True),
        sa.Column("embed_threshold", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("anchor", "attribute_name"),
    )
    op.create_table(
        "dm_anchor_attributes_meta",
        sa.Column("anchor", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("anchor", "attribute_name"),
    )
    op.create_table(
        "dm_conversation_lifecycle",
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("event"),
    )
    op.create_table(
        "dm_conversation_lifecycle_meta",
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("event"),
    )
    op.create_table(
        "dm_link_attributes",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("data_example", sa.String(), nullable=True),
        sa.Column("embeddable", sa.Boolean(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("dtype", sa.String(), nullable=True),
        sa.Column("embed_threshold", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("link", "attribute_name"),
    )
    op.create_table(
        "dm_link_attributes_meta",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("link", "attribute_name"),
    )
    op.create_table(
        "dm_prompts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "dm_prompts_meta",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "dm_queries",
        sa.Column("query_name", sa.String(), nullable=False),
        sa.Column("query_example", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("query_name"),
    )
    op.create_table(
        "dm_queries_meta",
        sa.Column("query_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("query_name"),
    )
    op.create_table(
        "ensure_memgraph_edge_indexes_3ad015600c_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "ensure_memgraph_node_indexes_ec2e99917e_meta",
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("attribute_name"),
    )
    op.create_table(
        "generate_embeddings_1976c99215_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.create_table(
        "generate_embeddings_804e595250_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "memgraph_anchor_indexes", sa.Column("anchor", sa.String(), nullable=False), sa.PrimaryKeyConstraint("anchor")
    )
    op.create_table(
        "memgraph_anchor_indexes_meta",
        sa.Column("anchor", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("anchor"),
    )
    op.create_table(
        "memgraph_anchor_vector_indexes",
        sa.Column("anchor", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("anchor", "attribute_name"),
    )
    op.create_table(
        "memgraph_anchor_vector_indexes_meta",
        sa.Column("anchor", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("anchor", "attribute_name"),
    )
    op.create_table(
        "memgraph_link_indexes", sa.Column("link", sa.String(), nullable=False), sa.PrimaryKeyConstraint("link")
    )
    op.create_table(
        "memgraph_link_indexes_meta",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("link"),
    )
    op.create_table(
        "memgraph_link_vector_indexes",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("link", "attribute_name"),
    )
    op.create_table(
        "memgraph_link_vector_indexes_meta",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("attribute_name", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("link", "attribute_name"),
    )
    op.drop_table("dm_attributes_v2")
    op.drop_table("ensure_memgraph_indexes_2de7695278_meta")
    op.drop_table("memgraph_indexes")
    op.drop_table("generate_embeddings_e949b6491e_meta")
    op.drop_table("dm_attributes_v2_meta")
    op.drop_table("memgraph_vector_indexes")
    op.drop_table("memgraph_indexes_meta")
    op.drop_table("generate_embeddings_634a8be398_meta")
    op.drop_table("memgraph_vector_indexes_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memgraph_vector_indexes_meta",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", name=op.f("memgraph_vector_indexes_meta_pkey")),
    )
    op.create_table(
        "generate_embeddings_634a8be398_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id", "to_node_id", "edge_label", name=op.f("generate_embeddings_634a8be398_meta_pkey")
        ),
    )
    op.create_table(
        "memgraph_indexes_meta",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", name=op.f("memgraph_indexes_meta_pkey")),
    )
    op.create_table(
        "memgraph_vector_indexes",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("anchor", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("link", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", name=op.f("memgraph_vector_indexes_pkey")),
    )
    op.create_table(
        "dm_attributes_v2_meta",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("anchor", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", "anchor", name=op.f("dm_attributes_v2_meta_pkey")),
    )
    op.create_table(
        "generate_embeddings_e949b6491e_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type", name=op.f("generate_embeddings_e949b6491e_meta_pkey")),
    )
    op.create_table(
        "memgraph_indexes",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("attribute_name", name=op.f("memgraph_indexes_pkey")),
    )
    op.create_table(
        "ensure_memgraph_indexes_2de7695278_meta",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", name=op.f("ensure_memgraph_indexes_783e90e30d_meta_pkey")),
    )
    op.create_table(
        "dm_attributes_v2",
        sa.Column("attribute_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("anchor", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("link", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("data_example", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("embeddable", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("query", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("dtype", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("embed_threshold", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("attribute_name", "anchor", name=op.f("dm_attributes_v2_pkey")),
    )
    op.drop_table("memgraph_link_vector_indexes_meta")
    op.drop_table("memgraph_link_vector_indexes")
    op.drop_table("memgraph_link_indexes_meta")
    op.drop_table("memgraph_link_indexes")
    op.drop_table("memgraph_anchor_vector_indexes_meta")
    op.drop_table("memgraph_anchor_vector_indexes")
    op.drop_table("memgraph_anchor_indexes_meta")
    op.drop_table("memgraph_anchor_indexes")
    op.drop_table("generate_embeddings_804e595250_meta")
    op.drop_table("generate_embeddings_1976c99215_meta")
    op.drop_table("ensure_memgraph_node_indexes_ec2e99917e_meta")
    op.drop_table("ensure_memgraph_edge_indexes_3ad015600c_meta")
    op.drop_table("dm_queries_meta")
    op.drop_table("dm_queries")
    op.drop_table("dm_prompts_meta")
    op.drop_table("dm_prompts")
    op.drop_table("dm_link_attributes_meta")
    op.drop_table("dm_link_attributes")
    op.drop_table("dm_conversation_lifecycle_meta")
    op.drop_table("dm_conversation_lifecycle")
    op.drop_table("dm_anchor_attributes_meta")
    op.drop_table("dm_anchor_attributes")
    # ### end Alembic commands ###
