"""simplify embedding steps

Revision ID: e70f049dd39f
Revises: 513bf0d273b0
Create Date: 2025-12-18 21:27:41.589193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e70f049dd39f"
down_revision: Union[str, None] = "513bf0d273b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generate_embeddings_3c11efed1b_meta",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type"),
    )
    op.create_table(
        "generate_embeddings_698f247fd3_meta",
        sa.Column("from_node_id", sa.String(), nullable=False),
        sa.Column("to_node_id", sa.String(), nullable=False),
        sa.Column("edge_label", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id", "edge_label"),
    )
    op.drop_table("store_pgvector_edges_899a47ab38_meta")
    op.drop_table("store_pgvector_nodes_572246caf2_meta")
    op.drop_table("generate_embeddings_e51be7175e_meta")
    op.drop_table("embedded_edges_meta")
    op.drop_table("embedded_nodes_meta")
    op.drop_table("generate_embeddings_38d4236c15_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generate_embeddings_38d4236c15_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type", name=op.f("generate_embeddings_38d4236c15_meta_pkey")),
    )
    op.create_table(
        "embedded_nodes_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type", name=op.f("embedded_nodes_meta_pkey")),
    )
    op.create_table(
        "embedded_edges_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("from_node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id",
            "to_node_id",
            "from_node_type",
            "to_node_type",
            "edge_label",
            name=op.f("embedded_edges_meta_pkey"),
        ),
    )
    op.create_table(
        "generate_embeddings_e51be7175e_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id", "to_node_id", "edge_label", name=op.f("generate_embeddings_e51be7175e_meta_pkey")
        ),
    )
    op.create_table(
        "store_pgvector_nodes_572246caf2_meta",
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("node_id", "node_type", name=op.f("store_pgvector_nodes_572246caf2_meta_pkey")),
    )
    op.create_table(
        "store_pgvector_edges_899a47ab38_meta",
        sa.Column("from_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("to_node_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("edge_label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "from_node_id", "to_node_id", "edge_label", name=op.f("store_pgvector_edges_899a47ab38_meta_pkey")
        ),
    )
    op.drop_table("generate_embeddings_698f247fd3_meta")
    op.drop_table("generate_embeddings_3c11efed1b_meta")
    # ### end Alembic commands ###
