"""add tests db store

Revision ID: a726164a3da7
Revises: 05aeb3cee9a6
Create Date: 2025-12-03 16:40:44.347364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a726164a3da7"
down_revision: Union[str, None] = "05aeb3cee9a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eval_tests",
        sa.Column("judge_model", sa.String(), nullable=False),
        sa.Column("judge_prompt_id", sa.String(), nullable=False),
        sa.Column("dm_id", sa.String(), nullable=False),
        sa.Column("pipeline_model", sa.String(), nullable=False),
        sa.Column("embeddings_model", sa.String(), nullable=False),
        sa.Column("embeddings_dim", sa.Integer(), nullable=False),
        sa.Column("gds_question", sa.String(), nullable=False),
        sa.Column("question_context", sa.String(), nullable=True),
        sa.Column("gds_answer", sa.String(), nullable=True),
        sa.Column("llm_answer", sa.String(), nullable=True),
        sa.Column("tool_calls", sa.String(), nullable=True),
        sa.Column("test_status", sa.String(), nullable=True),
        sa.Column("eval_judge_comment", sa.String(), nullable=True),
        sa.Column("test_date", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "judge_model",
            "judge_prompt_id",
            "dm_id",
            "pipeline_model",
            "embeddings_model",
            "embeddings_dim",
            "gds_question",
        ),
    )
    op.create_table(
        "eval_tests_meta",
        sa.Column("judge_model", sa.String(), nullable=False),
        sa.Column("judge_prompt_id", sa.String(), nullable=False),
        sa.Column("dm_id", sa.String(), nullable=False),
        sa.Column("pipeline_model", sa.String(), nullable=False),
        sa.Column("embeddings_model", sa.String(), nullable=False),
        sa.Column("embeddings_dim", sa.Integer(), nullable=False),
        sa.Column("gds_question", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "judge_model",
            "judge_prompt_id",
            "dm_id",
            "pipeline_model",
            "embeddings_model",
            "embeddings_dim",
            "gds_question",
        ),
    )
    op.create_table(
        "judge_tests_046730c9c6_meta",
        sa.Column("gds_question", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("gds_question"),
    )
    op.create_table(
        "tests_grist_meta",
        sa.Column("judge_model", sa.String(), nullable=False),
        sa.Column("judge_prompt_id", sa.String(), nullable=False),
        sa.Column("dm_id", sa.String(), nullable=False),
        sa.Column("pipeline_model", sa.String(), nullable=False),
        sa.Column("embeddings_model", sa.String(), nullable=False),
        sa.Column("embeddings_dim", sa.Integer(), nullable=False),
        sa.Column("gds_question", sa.String(), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "judge_model",
            "judge_prompt_id",
            "dm_id",
            "pipeline_model",
            "embeddings_model",
            "embeddings_dim",
            "gds_question",
        ),
    )
    op.create_table(
        "upload_tests_c054a42bc8_meta",
        sa.Column("judge_model", sa.String(), nullable=False),
        sa.Column("pipeline_model", sa.String(), nullable=False),
        sa.Column("embeddings_dim", sa.Integer(), nullable=False),
        sa.Column("judge_prompt_id", sa.String(), nullable=False),
        sa.Column("dm_id", sa.String(), nullable=False),
        sa.Column("embeddings_model", sa.String(), nullable=False),
        sa.Column("gds_question", sa.String(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "judge_model",
            "pipeline_model",
            "embeddings_dim",
            "judge_prompt_id",
            "dm_id",
            "embeddings_model",
            "gds_question",
        ),
    )
    op.drop_table("tests_meta")
    op.drop_table("judge_tests_0ef119aa17_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "judge_tests_0ef119aa17_meta",
        sa.Column("gds_question", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("gds_question", name=op.f("judge_tests_0ef119aa17_meta_pkey")),
    )
    op.create_table(
        "tests_meta",
        sa.Column("judge_model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("judge_prompt_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("dm_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("pipeline_model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("embeddings_model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("embeddings_dim", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("gds_question", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("create_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("update_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("process_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("delete_ts", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "judge_model",
            "judge_prompt_id",
            "dm_id",
            "pipeline_model",
            "embeddings_model",
            "embeddings_dim",
            "gds_question",
            name=op.f("tests_meta_pkey"),
        ),
    )
    op.drop_table("upload_tests_c054a42bc8_meta")
    op.drop_table("tests_grist_meta")
    op.drop_table("judge_tests_046730c9c6_meta")
    op.drop_table("eval_tests_meta")
    op.drop_table("eval_tests")
    # ### end Alembic commands ###
